version: "3.8"
services: 
    server:
        container_name: server
        build:
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
        ports: 
            - "8080:80"
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/html
        depends_on: 
            - php
            - mysql
    php:
        container_name: php
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes: 
            - ./src:/var/www/html:delegated
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports: 
            - 3306:3306
        env_file: 
            - ./env/mysql.env
    composer:
        container_name: composer
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
        volumes: 
            - ./src:/var/www/html
    artisan:
        container_name: artisan
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes: 
            - ./src:/var/www/html
        entrypoint: ["php","/var/www/html/artisan"]
    npm:
        container_name: npm
        image: node:14
        working_dir: /var/www/html
        entrypoint: ["npm"]
        volumes: 
            - ./src:/var/www/html
        